### ISSUE TITLE
支持python 3.10

### ISSUE THREAD

**Issue by wwhyjst** [sygslhy/image-io#5]
你好 请问可以继续支持 python 3.10 吗 我看新版本只支持3.12了 我们有些旧环境还是3.10的 可以麻烦继续支持下吗 万分感谢！

**Comment by sygslhy** [comment]
Hello , thanks for using cxx-image-io package, indeed, I removed 3.10 and 3.11 supporting recently, So what about I keep to support the same versions as numpy package support python >= 3.10. as long as this package require numpy, it will be good it aligns to numpy python versions supports.

**Comment by sygslhy** [comment]
new version 0.0.17 is uploaded to PYPI , this version support from python 3.10 to 3.13
